# Define your openstack VM nodes with ip and password info
control-1:
    ip:
    user: root
    password: ''
    role: controller
control-2:
    ip:
    user: root
    password: ''
    role: controller
control-3:
    ip:
    user: root
    password: ''
    role: controller
compute-1:
    ip:
    user: root
    password: ''
    role: compute

compute-2:
    ip:
    user: root
    password: ''
    role: compute
