provider: {ProviderExisting: [{host: 10.86.7.199, username: root, password: openstack}]}
deployer:  {DeployerExisting: {end_point: "http://172.17.35.20:5000/v2.0", cloud: bxb, user: admin, tenant: admin, admin: admin, password: mEwyFvAJdFdC8KG2XUqauDzDU}}
runner:  {RunnerRally: {cloud: bxb, task-yaml: task-rally.yaml}}
