deployer1: {lab.deployers.deployer_existing_osp7.DeployerExistingOSP7: {cloud: g10, hardware-lab-config: g10.yaml }}
deployer2: {lab.deployers.deployer_vts.DeployerVts: {'images-location': 'http://172.29.173.233/vts/nightly-2016-03-14/'}}
