deployer: {lab.deployers.deployer_mercury.DeployerMercury: {'installer-image': 'http://cloud-releases.cisco.com/mercury/releases/mercury-sprints/20160317_1759-mercury-rhel7-osp7/installer.20160317_1759-mercury-rhel7-osp7.tgz',
                                                            'installer-checksum': '79432e5fb8ac9c2c0d5c90f468bcd548d90a07b94d89963eec558ceeb04f54d0',
                                                            'hardware-lab-config': 'i13'}}
