---

- hosts: server1
  gather_facts: False
  vars_files:
    - config.yaml
  vars:
    work_dir: "{{ workspace }}/{{ inventory_hostname }}}"
    work_dir_vtc: "{{ work_dir }}/vtc"
    work_dir_xrnc: "{{ work_dir }}/xrnc"
    vtc: "{{ vts_hosts[inventory_hostname]['vtc'] }}"
    xrnc: "{{ vts_hosts[inventory_hostname]['xrnc'] }}"
    xrvr: "{{ vts_hosts[inventory_hostname]['xrvr'] }}"
  tasks:
    - include: tasks/add_vts_hosts.yaml
    - include: tasks/destroy.yaml
    - include: tasks/create_vtc.yaml
    - include: tasks/create_xrnc.yaml

- hosts: xrvr
  gather_facts: False
  connection: local
  vars_files:
    - config.yaml
  tasks:
    - include: tasks/xrvr_day0.yaml

- hosts: vtc
  gather_facts: False
  vars_files:
    - config.yaml
  tasks:
    - include: tasks/vtc_day0.yaml

- hosts: xrnc
  gather_facts: False
  tasks:
    - include: tasks/setupXRNC_HA.yaml
