---

- hosts: server1
  vars_files:
    - config.yaml
  roles:
    - { role: redhat-subscription, when: ansible_distribution == "RedHat"}
    - nested-virtaulization
    - kvm
    - ovs
    - ovs-bridges
