---

- hosts: server1
  vars:
    https_proxy: "{{proxy| default('')}}"
  vars_files:
    - config.yaml
  pre_tasks:
    - command: "/usr/bin/cat /sys/module/kvm_intel/parameters/nested"
      register: nested_virtualization

    - include: tasks/add_api_ip.yaml
    - include: tasks/pip.yaml
  roles:
    - nested-virtaulization
    - kvm
    - ovs
    - ovs-bridges


