---

- hosts: server1
  vars_files:
    - config.yaml
  pre_tasks:
    - name: "Add vtc_api_vip ip address to a interface to be sure server can go to WWW"
      shell: "ip address add {{ vtc_api_vip }}/{{ networks.api.cidr }} dev a || true"
    - name: "Change default gateway to {{ networks.api.gateway }} dev a"
      shell: "ip route del default || ip route add default via {{ networks.api.gateway }} dev a"

    - command: "/usr/bin/cat /sys/module/kvm_intel/parameters/nested"
      register: nested_virtualization
    - command: "which virsh"
      register: virsh_location
    - command: "which ovs-vsctl"
      register: ovsvsctl_location
  roles:
    - { role: redhat-subscription, when: ansible_distribution == "RedHat" }
    - { role: nested-virtaulization, when: nested_virtualization.stdout == "N" }
    - { role: kvm, when: virsh_location.rc == 1 }
    - { role: ovs, when: ovsvsctl_location.rc == 1 }
    - ovs-bridges
  environment: "{{ environment }}"
