---

- debug: var=nested_virtualization
- name: "Enable 'options kvm-intel nested=1'"
  command: "/usr/bin/echo 'options kvm-intel nested=1' > /etc/modprobe.d/kvm-intel.conf"
- name: rmmod
  command: "/usr/sbin/rmmod kvm_intel"
- name: modprobe
  command: "/usr/sbin/modprobe kvm_intel"
