provider: {ProviderExisting: [{host: 10.23.230.134, username: root, password: cisco123}]}
deployer:  {DeployerExisting: {end_point: 10.11.12.101, cloud: g10, user: admin, tenant: admin, admin: admin, password: 7ece5c821b6c2b1c888c58f59867f7a09be40c69}}
runner:  {RunnerRally: {cloud: g10, task-yaml: task-rally.yaml}}
