lab-id: 10 # integer in ranage (0,99). supposed to be unique in current L2 domain since used in MAC pools
user-net: {cidr: 10.23.230.128/27, vlan: 177, iface-name: mgmt} # used for normal user traffic
mgmt-net: {cidr: 10.23.228.224/27, vlan: 157, start: 5, end: 15} # used for UCSM KVM IPMI
undercloud-net: {cidr: 10.11.12.0/24, vlan: 3333} # used for internal pxe bootstrapping of overcloud-node
ucsm: {host: 10.23.228.253, username: admin, password: cisco, director-profile: DIRECTOR, uplink_ports: ['1/47', '1/48']}
n9k: {host: 10.30.119.100, username: admin, password: CTO1234!}
cobbler: {host: 172.29.74.8, username: cobbler, password: cobbler, iface-name: PXE-EXT}
