lab-id: 8 # integer in ranage (0,99). supposed to be unique in current L2 domain since used in MAC pools
is-add-sriov: False
mgmt-net:    {                                           vlan: 8,                         cidr: 10.30.119.0/24, start: 102, end: 105} # used for UCSM KVM IPMI
user-net:    {mac-tmpl: '{lab_id:02}:25:B5:AA:{b_c_id}', vlan: 174,  iface-name: user,    cidr: 10.23.230.64/27}    # used for normal user traffic
pxe-ext-net: {mac-tmpl: '{lab_id:02}:25:B5:FF:{b_c_id}', vlan: 1,    iface-name: pxe-ext, cidr: 169.254.4.0/24,} # used for external pxe bootstrapping of director
pxe-int-net: {mac-tmpl: '{lab_id:02}:25:B5:EE:{b_c_id}', vlan: 3333, iface-name: pxe-int, cidr: 10.11.12.0/24} # used for internal pxe bootstrapping of overcloud-node
eth0-net:    {mac-tmpl: '{lab_id:02}:25:B5:00:{b_c_id}', vlan: 3000, iface-name: eth0, } # used for eth0 network - current restriction of ucsm plugin
eth1-net:    {mac-tmpl: '{lab_id:02}:25:B5:11:{b_c_id}', vlan: 3001, iface-name: eth1, } # used for eth1 network - current restriction of ucsm plugin
ucsm: {host: 10.30.119.67, username: admin, password: cisco, director-profile: DIRECTOR, director-server-id: 1, uplink-ports: ['1/9', '1/10'], uplink-vpc-id: 81}
n9k: {host: 172.31.229.207, username: admin, password: CTO1234!}
cobbler: {host: 172.29.74.8, username: cobbler, password: cobbler}
rh-secret: http://172.29.173.233/redhat/osp7/redhat-developers-account.yaml # login-password info for RH dev account used in director's registration
