provider: {ProviderExisting: [{host: 172.29.86.178, username: root, password: cisco123}]}
deployer:  {DeployerExisting: {end_point: "http://172.29.86.178:5000/v2.0", cloud: jaya, user: admin, tenant: admin, admin: admin, password: lab}}
runner:  {RunnerRally: {cloud: jaya, task-yaml: task-rally.yaml}}
