provider: {ProviderLibvirt: {
            lab_id: 77,
            username: cisco,
            password: cisco123,
            networks: [41, 61],
            instances: [{hostname: dibbler, on_nets: [41, 61],
                        image_url: 'http://172.29.173.233/fedora/Fedora-Cloud-Base-22-20150521.x86_64.qcow2',
                        image_checksum: a5d6da626667e21f7de04202c8da5396c0fc7e26872d016f3065f1110cff7962},
                        {hostname: aio, on_nets: [41, 61],
                        image_url: 'http://172.29.173.233/fedora/Fedora-Cloud-Base-22-20150521.x86_64.qcow2',
                        image_checksum: a5d6da626667e21f7de04202c8da5396c0fc7e26872d016f3065f1110cff7962}
                       ]
          }}
deployer1: {DeployerDibbler: {prefix: '2222:2222:2222::/48', hostname: dibbler}}
deployer2: {DeployerDevstack: {password: cisco123, server_config_pairs: [{hostname: aio, devstack_config: aio-pd}]}}
