provider1: {ProviderExisting: [{host: 10.23.230.132, username: root, password: cisco123}]}
provider2: {ProviderUCSM: {host: 10.23.228.253, username: admin, password: cisco}}
deployer: {DeployerOSP7: {rdo_account: ymorkovn@cisco.com,
                          rdo_password: 280778,
                          rdo_pool_id: 8a85f9864cfbfc41014cfc065097403b,
                          undercloud_network_cidr: '10.11.12.0/24',
                          images_url: 'http://172.29.173.233/redhat/osp7',
                          director: 10.23.230.132,
                          cloud_password: cisco123
                          }
          }
