provider1: {ProviderCobbler: {host: 172.29.74.8,
                             user: cobbler,
                             password: cobbler,
                             system_password: cisco123,
                             force_pxe_boot: True,
                             selector: {name: G10-DIRECTOR, owners: kshileev}
                             }
          }
provider2: {ProviderUCSM:    {yaml_path: g10.yaml}}
deployer: {DeployerOSP7: {rh-secret: http://172.29.173.233/redhat/osp7/redhat-developers-account.yaml,
                          cloud_password: 'cisco123',
                          director: 10.23.230.132,
                          images_url: 'http://172.29.173.233/redhat/osp7',
                          undercloud_network_cidr: '10.11.12.0/24'
                          }
          }

