---

- name: "Install rpm package"
  yum:
    name: "{{ item }}"
  with_items:
    - qemu-kvm
    - qemu-img
    - virt-manager
    - libvirt
    - libvirt-python
    - libvirt-client
    - virt-install
    - virt-viewer
    - genisoimage
    - libffi-devel
- name: Enable libvirtd
  shell: "systemctl enable libvirtd"
- name: Start libvirtd
  shell: "systemctl start libvirtd"
- command: "which virsh"
  register: virsh_bin
- name: Call 'virsh list'
  shell: "virsh list"
