---

- set_fact:
    ns_path: /etc/sysconfig/network-scripts/
    bonds:
      a:
        ifcfg: ifcfg-a
        ovs_bridge: br-api
      mx:
        ifcfg: ifcfg-mx
        ovs_bridge: br-mgmt
      t:
        ifcfg: ifcfg-t
        ovs_bridge: br-tenant
    bridges:
      br-api:
        ifcfg: ifcfg-br-api
      br-mgmt:
        ifcfg: ifcfg-br-mgmt
      br-tenant:
        ifcfg: ifcfg-br-tenant
- name: "Create ovs-bridge configs"
  template:
    src: "templates/ovs_bridge.jinja2"
    dest: "{{ ns_path + item.value.ifcfg }}"
    force: no
  with_dict: "{{ bridges }}"
- name: "Move bond paramters to bridges"
  shell: "p=$(cat {{ ns_path + item.0.ifcfg }} | awk -F'=' '/{{ item.1 }}/{print $2}');  if [ -n \"$p\" ]; then echo \"{{ item.1 }}=$p\" >> {{ ns_path + bridges[item.0.ovs_bridge].ifcfg }} ; fi"
  with_nested:
    - "{{ bonds.values() }}"
    - ['IPADDR', 'NETMASK', 'GATEWAY']
- name: "Create bond configs"
  template:
    src: "templates/ovs_port_bond.jinja2"
    dest: "{{ ns_path + item.value.ifcfg }}"
  with_dict: "{{ bonds }}"
- name: "Remove all ifcfg-enp* interface config files. Workaround for a bug"
  command: "rm -f /etc/sysconfig/network-scripts/ifcfg-enp*"
- name: "Restart network-manager"
  shell: "for int in $(ip -o link | grep -o -E ' (p|t|mx|e|a)1' ); do ifdown $int; done; systemctl restart network;"
