---

- shell: "which ovs-vsctl"
  register: ovsvsctl_location
  ignore_errors: yes
- name: "Check br-api exists"
  shell: "ovs-vsctl br-exists br-api"
  register: br_api_exists
  when: ovsvsctl_location.get("rc", 1) == 0

- name: "Add vtc_api_vip ip address to a interface to be sure server can go to WWW"
  shell: "ip a show a | grep {{ vtc_api_vip }}/{{ networks.api.cidr }} || ip address add {{ vtc_api_vip }}/{{ networks.api.cidr }} dev a"
  when: ovsvsctl_location.get("rc", 1) == 1 or br_api_exists.get("rc", 2) == 2

- name: "Change default gateway to {{ networks.api.gateway }} dev a"
  shell: "ip route del default; ip route add default via {{ networks.api.gateway }} dev a"
  when: ovsvsctl_location.get("rc", 1) == 1 or br_api_exists.get("rc", 2) == 2
  ignore_errors: yes

- name: "Add vtc_api_vip ip address to br-api interface to be sure server can go to WWW"
  shell: "ip a show br-api | grep {{ vtc_api_vip }}/{{ networks.api.cidr }} || ip address add {{ vtc_api_vip }}/{{ networks.api.cidr }} dev br-api"
  when: ovsvsctl_location.get("rc", 1) == 0 and br_api_exists.get("rc", 2) == 0
- name: "Change default gateway to {{ networks.api.gateway }} dev br-api"
  shell: "ip route del default; ip route add default via {{ networks.api.gateway }} dev br-api"
  when: ovsvsctl_location.get("rc", 1) == 0 and br_api_exists.get("rc", 2) == 0