---

- add_host:
    name: "{{ vtc['hostname']  }}"
    ansible_ssh_host: "{{ vtc['api_ip'] }}"
    ansible_ssh_user: "{{ user }}"
    ansible_ssh_pass: "{{ password }}"
    props: "{{ vtc }}"
    ansible_become_pass: "{{ password }}"
    groups: vtc

#- add_host:
#    name: "{{ xrnc['hostname']  }}"
#    ansible_ssh_host: "{{ xrnc['mgmt_ip'] }}"
#    ansible_ssh_user: "cisco"
#    ansible_ssh_pass: "{{ password }}"
#    ansible_become_pass: "{{ password }}"
#    props: "{{ xrnc }}"
#    peer_xrnc_ip: "0.0.0.0"
#    groups: xrnc

- add_host:
    name: "{{ xrvr['hostname']  }}"
    ansible_ssh_host: "{{ xrnc['mgmt_ip'] }}"
    ansible_ssh_user: "admin"
    ansible_ssh_pass: "cisco123"
    props: "{{ xrvr }}"
    groups: xrvr
