---

- file: dest={{ work_dir }} state=directory
- file: dest={{ work_dir_vtc }} state=directory recurse=yes mode=0744 owner=qemu group=qemu

# Create VTC
- name: "Download VTC image {{ vtc_qcow }}"
  command: "/usr/bin/curl {{ vtc_qcow }} -o {{ work_dir_vtc }}/vtc.qcow2"
- file:
    dest: "{{ work_dir_vtc }}/vtc.qcow2"
    owner: qemu
    group: qemu
- template:
    src: templates/vtc/config.txt.jinja2
    dest: "{{ work_dir_vtc }}/config.txt"
- template:
    src: templates/vtc/vtc.xml.jinja2
    dest: "{{ work_dir_vtc }}/vtc.xml"
- name: "Create config.iso for VTC virtual machine"
  command: "/usr/bin/mkisofs -o {{ work_dir_vtc }}/config.iso {{ work_dir_vtc }}/config.txt"
- name: "Create VTC virtual machine"
  command: "/usr/bin/virsh create {{ work_dir_vtc }}/vtc.xml"
- name: "Wait for VTC port 22"
  wait_for: host={{ vtc['api_ip'] }} port=22
- name: "Wait for VTC port 8443"
  wait_for: host={{ vtc['api_ip'] }} port=8443
- pause: seconds=60
- name: "Open VTC UI first time"
  uri:
    url: "https://{{ vtc['api_ip'] }}:8443/VTS/"
    validate_certs: no
    timeout: 180
- name: "Change VTC UI admin password to {{ vtc_password }}"
  vtcui_password_change:
    vtc_ip: "{{ vtc['api_ip'] }}"
    user: "{{ user }}"
    password: "admin"
    new_password: "{{ vtc_password }}"
