---

- file: dest={{ work_dir }} state=directory
- file: dest={{ work_dir_vtc }} state=directory recurse=yes mode=0744 owner=qemu group=qemu

# Create VTC
- name: "Download VTC image {{ vtc_qcow }}"
  get_url:
    url: "{{ vtc_qcow }}"
    dest: "{{ work_dir_vtc }}/vtc.qcow2"
    force: no
    owner: qemu
    group: qemu
- template:
    src: templates/vtc/config.txt.jinja2
    dest: "{{ work_dir_vtc }}/config.txt"
- template:
    src: templates/vtc/vtc.xml.jinja2
    dest: "{{ work_dir_vtc }}/vtc.xml"
- name: "Create config.iso for VTC virtual machine"
  command: "/usr/bin/mkisofs -o {{ work_dir_vtc }}/config.iso {{ work_dir_vtc }}/config.txt"
- name: "Create VTC virtual machine"
  command: "/usr/bin/virsh create {{ work_dir_vtc }}/vtc.xml"
- name: "Wait for VTC port 22"
  wait_for: 
    host: "{{ vtc['api_ip'] }}" 
    port: 22
    timeout: 720
  delegate_to: 127.0.0.1
- name: "Wait for VTC port 8443"
  wait_for: host={{ vtc['api_ip'] }} port=8443
  delegate_to: 127.0.0.1
- pause: seconds=120

- name: "Fix VTC UI: stop apache tomcat"
  shell: "service tomcat stop"
  become: yes
  delegate_to: "{{item}}"
  with_items: "{{groups['vtc']}}"
- name: "Fix VTC UI: remove old VTS folder"
  shell: "rm -rf /opt/cisco/apache/apache-tomcat-7.0.68/webapps/VTS"
  become: yes
  become_method: sudo
  delegate_to: "{{item}}"
  with_items: "{{groups['vtc']}}"
- name: "Fix VTC UI: start apache tomcat"
  shell: "sudo service tomcat start"
  become: yes
  become_method: sudo
  delegate_to: "{{item}}"
  with_items: "{{groups['vtc']}}"
- pause: seconds=60
- name: "Fix VTC UI: chown VTS dir"
  shell: "chown -R tomcat:tomcat /opt/cisco/apache/apache-tomcat-7.0.68/webapps/VTS"
  become: yes
  become_method: sudo
  delegate_to: "{{item}}"
  with_items: "{{groups['vtc']}}"

- pause: seconds=120
- name: "Open VTC UI first time"
  uri:
    url: "https://{{ vtc['api_ip'] }}:8443/VTS/"
    validate_certs: no
    timeout: 600
  delegate_to: 127.0.0.1
- name: "Change VTC UI admin password to {{ vtc_password }}"
  vtcui_password_change:
    vtc_ip: "{{ vtc['api_ip'] }}"
    user: "{{ user }}"
    password: "admin"
    new_password: "{{ vtc_password }}"
  delegate_to: 127.0.0.1
