---

- file: dest={{ work_dir }} state=directory
- file: dest={{ work_dir_xrnc }} state=directory recurse=yes mode=0744 owner=qemu group=qemu

# Create XRNC
# create xrnc config iso on the VTC side
- name: "Upload system.cfg (XRNC config) to VTC virtual machine"
  template:
    src: templates/xrnc/system.cfg.jinja2
    dest: "/tmp/{{ xrnc['hostname'] }}.cfg"
  delegate_to: "{{ vtc['hostname'] }}"
- name: "Run build_vts_config_iso.sh script on the VTC side"
  command: "/opt/cisco/package/vts/bin/build_vts_config_iso.sh xrnc /tmp/{{ xrnc['hostname'] }}.cfg"
  delegate_to: "{{ vtc['hostname'] }}"
- name: "Fetch XRNC config.iso"
  fetch: dest=/tmp/xrnc_cfg.iso src=/home/admin/xrnc_cfg.iso flat=yes
  delegate_to: "{{ vtc['hostname'] }}"
- fetch: dest=/tmp/system.cfg src=/home/admin/xrnc_cfg_tmp/system.cfg flat=yes
  delegate_to: "{{ vtc['hostname'] }}"
- name: "Upload XRNC config.iso to a server where XRNC vm will be created"
  copy: src=/tmp/xrnc_cfg.iso dest={{ work_dir_xrnc }}
- copy: src=/tmp/system.cfg dest={{ work_dir_xrnc }}
# launch XRNC vm
- template:
    src: templates/xrnc/xrnc.xml.jinja2
    dest: "{{ work_dir_xrnc }}/xrnc.xml"
- name: "Download XRNC image {{ xrnc_qcow }}"
  get_url:
    url: "{{ xrnc_qcow }}"
    dest: "{{ work_dir_xrnc }}/xrnc.qcow2"
    force: no
    owner: qemu
    group: qemu
- name: "Create XRNC virtual machine"
  command: "/usr/bin/virsh create {{ work_dir_xrnc }}/xrnc.xml"
- name: "Wait for XRNC port 22"
  wait_for: host={{ xrnc['mgmt_ip'] }} port=22
  delegate_to: 127.0.0.1
# Let XRVR to boot and configure itself
- pause: minutes=5

