---

- name: Destroy old VTC virtual machine
  command: "/usr/bin/virsh destroy {{ vtc['hostname'] }}"
  ignore_errors: yes
- name: Destroy old XRNC virtual machine
  command: "/usr/bin/virsh destroy {{ xrnc['hostname'] }}"
  ignore_errors: yes
