---
  NovaServers.boot_and_delete_multiple_servers:
   {% for n_tenants in range(10, 50, 10) %}
    -
      args:
        image:
          name: "^cirros.*img$"
        flavor:
          name: "m1.tiny"
        count: 2
      runner:
        type: "constant"
        times: {{n_tenants}}
        concurrency: 7
      context:
        users:
          tenants: {{n_tenants}}
          users_per_tenant: 1
        network:
          networks_per_tenant: 2
  {% endfor %}
