[DEFAULT]
director_node_hostname = g10-director.ctocllab.cisco.com
director_node_ssh_ip = 10.23.230.132
director_node_ssh_username = root

undercloud_vlan = 177 # user network

[cobbler]
osp_directory_node = G10-DIRECTOR
skip = False

[switch_config]
skip = True

[ansible]
rhel_pool = 8a85f9864cfbfc41014cfc065097403b
rhel_username = ymorkovn@cisco.com
rhel_password = 280778

neutron_mechanism_drivers = openvswitch,cisco_ucsm
network_ucsm_ip = 10.23.228.253
network_ucsm_username = admin
network_ucsm_password = cisco
network_ucsm_host_list = 00:25:B5:10:00:02:QA3-2,00:25:B5:10:00:03:QA1,00:25:B5:10:00:05:QA3,00:25:B5:10:00:04:QA2

overcloud_control_scale = 3
overcloud_compute_scale = 1

single_nic = eth0
#10.30.117.192/27
#vlan 120
undercloud_vlan = 2222 # vlan on pxe-int for initial boot
undercloud_network_cidr =  169.254.0.0/24
undercloud_network_gateway = 169.254.0.1
undercloud_local_ip =  169.254.0.1/24
undercloud_local_ip_simple = 169.254.0.1
undercloud_local_interface = pxe-int
undercloud_dhcp_start = 169.254.0.31
undercloud_dhcp_end = 169.254.0.60

undercloud_masquerade_network = 10.23.230.64/27

undercloud_discovery_iprange = 169.254.0.10,169.254.0.30
undercloud_public_vip = 169.254.0.2/27
undercloud_admin_vip = 169.254.0.3/27

overcloud_vlan = 2000
overcloud_network_cidr = 20.0.0.0/24
overcloud_floating_ip_cidr = 20.0.0.0/24
overcloud_floating_ip_start = 20.0.0.10
overcloud_floating_ip_end = 20.0.0.200
overcloud_bm_network_gateway = 20.0.0.1

overcloud_nodes = {
                       "nodes":[
                          {
                             "pm_password":"cobbler",
                             "mac":["00:25:B5:10:EE:02"],
                             "pm_addr":"10.23.228.234",
                             "pm_type":"pxe_ipmitool",
                             "memory":256,
                             "disk":1112,
                             "arch":"x86_64",
                             "cpu":40,
                             "pm_user":"cobbler"
                          },
                          {
                             "pm_password":"cobbler",
                             "mac":["00:25:B5:10:EE:03"],
                             "pm_addr":"10.23.228.231",
                             "pm_type":"pxe_ipmitool",
                             "memory":256,
                             "disk":1112,
                             "arch":"x86_64",
                             "cpu":40,
                             "pm_user":"cobbler"
                          },
                          {
                             "pm_password":"cobbler",
                              "mac":["00:25:B5:10:EE:04"],
                              "pm_addr":"10.23.228.233",
                              "pm_type":"pxe_ipmitool",
                              "memory":256,
                              "disk":1112,
                              "arch":"x86_64",
                              "cpu":40,
                              "pm_user":"cobbler"
                           },
                          {
                             "pm_password":"cobbler",
                              "mac":["00:25:B5:10:EE:05"],
                              "pm_addr":"10.23.228.232",
                              "pm_type":"pxe_ipmitool",
                              "memory":256,
                              "disk":1112,
                              "arch":"x86_64",
                              "cpu":40,
                              "pm_user":"cobbler"
                           }
                       ]
                    }


[certification]
controller_host = ip
rhel_pool = 8a85f9864cfbfc41014cfc065097403b
rhel_username = ymorkovn@cisco.com
rhel_password = 280778
