lab-id: 10 # integer in ranage (0,99). supposed to be unique in current L2 domain since used in MAC pools
user-net: {cidr: 10.23.230.128/27, vlan: 177, iface-name: mgmt} # used for normal user traffic
mgmt-net: {cidr: 10.23.228.224/27, vlan: 157} # used for UCSM KVM IPMI
ucsm: {host: 10.23.228.253, username: admin, password: cisco, director-profile: DIRECTOR}
n9k: {host: 10.30.119.100, username: admin, password: CTO1234!}
cobbler: {host: 172.29.74.8, username: cobbler, password: cobbler, iface-name: PXE-EXT}

