Folder: Automation itself tests
Title: Test parallel workers
Description: Test to check that parallel infrastructure actually works
UniqueID: os-sqe-dev01
PossibleDrivers: [vts, vpp]

Workers:
- class: lab.monitors.empty_monitor.EmptyMonitor
  name: mon
  delay: 0
  run: [sce]
  pause: 2
  timeout: 360
  arg1 : 22
  arg2: 33

- class: lab.monitors.empty_monitor.EmptyMonitor
  name: sce
  delay: 3
  run: [di1, di2]
  pause: 3
  timeout: 360
  arg1 : 22
  arg2: 33

- class: lab.monitors.empty_monitor.EmptyMonitor
  name: di1
  delay: 20
  run: 2
  pause: 3
  timeout: 360
  arg1 : 22
  arg2: 33

- class: lab.monitors.empty_monitor.EmptyMonitor
  name: di2
  delay: [di1]
  run: 3
  pause: 3
  timeout: 360
  arg1 : 22
  arg2: 33
