---
# Used to test n9k monitor

- method: lab.monitors.nexus # try to test non existing n9k
  duration: 20
  period: 2
  name_or_ip: 1.1.1.1
  username: a
  password: b

- method: lab.monitors.nexus # try to test non existing n9k
  duration: 20
  period: 2
  is_show_details: True