- class: lab.monitors.socket_connect_to_port_monitor.SocketConnectToPort
  name: s150
  n_repeats: 10
  ip-port: 10.23.221.150:8888
  socket-timeout: 5
  delay: 1

- class: lab.monitors.socket_connect_to_port_monitor.SocketConnectToPort
  name: s151
  n_repeats: 10
  ip-port: 10.23.221.151:8888
  socket-timeout: 5
  delay: 1

- class: lab.monitors.socket_connect_to_port_monitor.SocketConnectToPort
  name: s152
  n_repeats: 10
  ip-port: 10.23.221.152:8888
  socket-timeout: 5
  delay: 1