---
- Folder: VTS PERF AND SCALE
- Title: no CSR, 5 PVP chains with 1M flows
- Description: runs number of perfomance benchmarks described in https://cisco.jiveon.com/docs/DOC-1711443. Target architecture is defined by pod on which this test is run.

- class: lab.scenarios.ntt_scenario.NttScenario
  name: NttScenario
  n_repeats: 1
  what-to-run: nfvbench  # might by nfvbench, csr, both
  csr-per-compute: not-used # special value 1 means just a single CSR, starting from 2 it will be considered as number of CRSs per compute node
  csr-sleep: not-used  # seconds between 2 successive openstack server create requests
  chain-type: PVP # possible values EXT PVP PVVP
  chain-count: 5  # number of concurrent chains
  flow-count: 1000000
