---
- Folder: VTS PERF AND SCALE
- Title: 10 CSR per compute, no nfvbench
- Description: runs number of perfomance benchmarks described in https://cisco.jiveon.com/docs/DOC-1711443. Target architecture is defined by pod on which this test is run.

- class: lab.scenarios.ntt_scenario.NttScenario
  name: NttScenario
  n_repeats: 1
  what-to-run: csr  # might by nfvbench, csr, both
  csr-per-compute: 10  # special value 1 means just a single CSR, starting from 2 it will be considered as number of CRSs per compute node
  csr-sleep: 5   # seconds between 2 successive openstack server create requests
  chain-type: not-used
  chain-count: not-used
  flow-count: not-used
  frame-size: not-used