---
- Folder: VTS PERF AND SCALE
- Title: 10 CSR per compute, no nfvbench
- Description: runs number of perfomance benchmarks described in https://cisco.jiveon.com/docs/DOC-1711443. Target architecture is defined by pod on which this test is run.

- class: lab.scenarios.ntt_scenario.NttScenario
  name: NttScenario
  n_repeats: 1
  what-to-run: csr  # might be nfvbench, csr, both
  csr-args: csr_create.sh 20 10 5 # <number of CSRs> <number of CSR per compute> <total time to sleep between successive nova boot
  csr-sleep: 5   # seconds between 2 successive openstack server create requests
  nfvbench-args: no-used
