---
- Folder: VTS PERF AND SCALE
- Title: 1 CSR, 1 EXT chain with 1k flows
- Description: runs number of perfomance benchmarks described in https://cisco.jiveon.com/docs/DOC-1711443. Target architecture is defined by pod on which this test is run.

- class: lab.scenarios.ntt_scenario.NttScenario
  name: NttScenario
  n_repeats: 1
  what-to-run: both  # might by nfvbench, csr, both
  csr-args: csr_create.sh 1 1 5 # <number of CSRs> <number of CSR per compute> <total time to sleep between successive nova boot
  nfvbench-args: --rate ndr_pdr --service-chain EXT --service-chain-count 1 --flow-count 1000 --frame-size 64 --frame-size IMIX --frame-size 1518
