---
- Folder: PERFOMANCE AND SCALE
- Description: runs iperf and reports its results

- class: lab.scenarios.vts_scenario.VtsScenario
  name: VtsScenario
  how-many-networks: 1
  how-many-servers: 2
  what-to-run-inside: iperf -n 10G  -M 9000
  n_repeats: 1
  uptime: 10
