---
- Folder: HIGH AVAILABILITY
- Title: Active DL tenenat iface down while adding OS servers
- Description: Validate Standby XRNC becomes "Active' when Active XRNC's eth0 is shut while new tenant VMs are being created

- class: lab.monitors.vts_monitor.VtsMonitor
  name: VtsMonitor
  delay: 0
  run: [VtsScenario]
  pause: 2
  timeout: 1000

- class: lab.scenarios.vts_scenario.VtsScenario
  name: VtsScenario
  delay: 0
  run: [VtsDisruptor]
  pause: 2
  timeout: 1000
  n_networks: 1
  n_servers: 1
  run_inside: ping
  uptime: 20

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: VtsDisruptor
  delay: 10
  run: 10
  pause: 10
  timeout: 1000
  node_to_disrupt: master-dl
  method_to_disrupt: isolate-from-t
  disrupt_time: 20