
Folder: HIGH AVAILABILITY
Title: Active VTC reboot while adding OS servers
Description: Validate Standby VTC becomes "Active' when Active VTC is rebooted while Tenant VMs are also being created

- class: lab.monitors.vts_monitor.VtsMonitor
  name: VtsMonitor
  delay: 0
  run: [VtsScenario]
  pause: 2
  timeout: 1000

- class: lab.scenarios.vts_scenario.VtsScenario
  name: VtsScenario
  delay: 0
  run: [VtsDisruptor]
  pause: 10
  timeout: 1000
  n_networks: 1
  n_servers: 2
  run_inside: ping
  uptime: 20

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: VtsDisruptor
  delay: 0
  run: 10
  pause: 30
  timeout: 1000
  node_to_disrupt: master-vtc
  method_to_disrupt: vm-reboot
  disrupt_time: 20