---
- Folder: HIGH AVAILABILITY
- Description: test it statically - run VM create - ping - delete cycle parametrized number of steps, in paralell do the same with disruptor, then make sure from log timestemps that disrupting while VM was provisioning
              indeed happend at least once.

- class: lab.monitors.vts_monitor.VtsMonitor
  period: 2
  run_while:
    - VtsDisruptor

- class: lab.scenarios.vts_scenario.VtsScenario
  how-many-networks: 1
  how-many-servers: 1
  run_while:
    - VtsDisruptor

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  delay: 20
  node-to-disrupt: master-dl
  method-to-disrupt: isolate-from-t
  n_repeats: 5
  downtime: 580
  uptime: 20
  set:
    - VtsDisruptor

# Validate Standby XRNC becomes "Active' when Active XRNC's eth0 is shut while new tenant VMs are being created