---
- Folder: HIGH AVAILABILITY
- Description: Validate Standby VTC is still running and in Standby mode when Standby  VTC is rebooted while existing tenant VMs are also being deleted

- class: lab.monitors.vts_monitor.VtsMonitor
  period: 2
  run_while:
    - vts-disruptor

- class: lab.scenarios.vts_delete_scenario.VtsDeleteScenario
  how-many-networks: 2
  how-many-servers: 10
  uptime: 120
  when:
    - vts-disruptor

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  delay: 20
  node-to-disrupt: slave-vtc
  method-to-disrupt: vm-reboot
  n_repeats: 1
  downtime: 460
  uptime: 120
  set:
    - vts-disruptor

# Validate Standby VTC is still running and in Standby mode when Standby  VTC is rebooted whileexisting tenant VMs are also being deleted