---
- Folder: HIGH AVAILABILITY
- Description: tc_vts_passive_vtc_isolate_from_mx first create OS VM then set DOWN MX interface for a while

- class: lab.monitors.vts_monitor.VtsMonitor
  name: VtsMonitor
  period: 2
  run_while:
    - VtsDisruptor

- class: lab.scenarios.vts_scenario.VtsScenario
  name: VtsScenario
  delay: 5
  how-many-networks: 1
  how-many-servers: 2
  what-to-run-inside: ping
  uptime: 20
  run_while:
    - VtsDisruptor

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: VtsDisruptor
  delay: 120
  node-to-disrupt: slave-vtc
  method-to-disrupt: isolate-from-mx
  n_repeats: 1
  downtime: 90
  uptime: 20

# Possible nodes to disrupt: 'active-vtc', 'passive-vtc', 'active-dl', 'passive-dl'
# Possible methods:  'isolate-from-mx', 'isolate-from-api', 'vm-shutdown', 'vm-reboot', 'corosync-stop', 'ncs-stop'