---
- Folder: HIGH AVAILABILITY
- Description: Validate Standby VTC becomes "Active' when Active VTC is rebooted while a compute node is added and deleted

- class: lab.monitors.vts_monitor.VtsMonitor
  run_while: disruptor-running

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  delay: 3
  downtime: 120
  uptime: 60
  node-to-disrupt: master-vtc
  method-to-disrupt: vm-reboot
  run_while:
    - deleting-compute
    - adding-compute
  set:
    - disruptor-running

- class: lab.scenarios.vts_delete_compute.VtsDeleteCompute
  n_repeats: 1
  set: deleting-compute

- class: lab.scenarios.vts_add_compute.VtsAddCompute
  run_after: deleting-compute
  n_repeats: 1
  set: adding-compute