---
- Folder: HIGH AVAILABILITY
- Description: Validate Standby XRNC becomes "Active' when Active XRNC is rebooted while adding a compute node

- class: lab.monitors.vts_monitor.VtsMonitor
  run_while: VtsDisruptor

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: disruptor-runnning
  delay: 3
  downtime: 120
  uptime: 60
  node-to-disrupt: master-dl
  method-to-disrupt: vm-shutdown
  run_while:
    - VtsDeleteCompute
    - VtsAddCompute

- class: lab.scenarios.vts_delete_compute.VtsDeleteCompute
  n_repeats: 1

- class: lab.scenarios.vts_add_compute.VtsAddCompute
  run_after: VtsDeleteCompute
  delay: 10
  n_repeats: 1
