---
- Folder: HIGH AVAILABILITY
- Description: Validate Standby VTC becomes "Active' when Active VTC is rebooted while existing tenant VMs are also being deleted
- class: lab.monitors.vts_monitor.VtsMonitor
  duration: 600
  period: 2

- class: lab.scenarios.vts_delete_scenario.VtsDeleteScenario
  how-many-networks: 2
  how-many-servers: 10
  uptime: 120
  n_repeats: 1

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  delay: 20
  node-to-disrupt: master-vtc
  method-to-disrupt: vm-reboot
  n_repeats: 1
  downtime: 460
  uptime: 120

# Validate Standby VTC becomes "Active' when Active VTC is rebooted while existing tenant VMs are also being deleted