---
# Project: Tcbr2p
# Title: XRNC HA failover by stoping the corosync on Active XRNC while tenant VMs are being added/deleted
# ID: Tcbr1444c
# Description: test it statically - run VM create - ping - delete cycle parametrized number of steps, in paralell do the same with disruptor, then make sure from log timestemps that disrupting while VM was provisioning
#              indeed happend at least once.

- class: lab.monitors.vts_monitor.VtsMonitor
  duration: 2000
  period: 2

- class: lab.scenarios.vts_scenario.VtsScenario
  how-many-networks: 1
  how-many-servers: 1
  how-many-times: 40

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  delay: 20
  node-to-disrupt: active-dl
  method-to-disrupt: corosync-stop
  how-many-times: 10
  downtime: 100
  uptime: 20
