---
- Folder: HIGH AVAILABILITY
- Description: first create OS VM then start disruptor
- class: lab.monitors.vts_monitor.VtsMonitor
  run_while:
    - vts-disruptor
  period: 2

- class: lab.scenarios.vts_scenario.VtsScenario
  delay: 20
  how-many-networks: 1
  how-many-servers: 3
  run_while:
    - vts-disruptor

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  delay: 20
  node-to-disrupt: master-dl
  method-to-disrupt: vm-reboot
  n_repeats: 2
  downtime: 90
  uptime: 270
  set:
    - vts-disruptor

# Possible nodes to disrupt: 'active-vtc', 'passive-vtc', 'active-dl', 'passive-dl'
# Possible methods:  'isolate-from-mx', 'isolate-from-api', 'vm-shutdown', 'vm-reboot', 'corosync-stop', 'ncs-stop'