---
- Folder: HIGH AVAILABILITY
- Description: re-boot master VTC and slave VTC, then create OS VM

- class: lab.monitors.vts_monitor.VtsMonitor
  name: VtsMonitor
  period: 2
  run_while:
    - VtsScenario

# wait for long time. Check if VTC HA comes up by booting up VMs
- class: lab.scenarios.vts_scenario.VtsScenario
  name: VtsScenario
  how-many-networks: 1
  how-many-servers: 3
  n_repeats: 1
  what-to-run-inside: ping
  uptime: 20
  run_after: [VtsDisruptorVtcMaster, VtsDisruptorVtcSlave]

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: VtsDisruptorVtcMaster
  delay: 3
  node-to-disrupt: master-vtc
  method-to-disrupt: vm-shutdown
  n_repeats: 1
  downtime: 90
  uptime: 20

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: VtsDisruptorVtcSlave
  delay: 3
  node-to-disrupt: slave-vtc
  method-to-disrupt: vm-shutdown
  n_repeats: 1
  downtime: 90
  uptime: 20

# Validate VTC Ha comes up properly after both Active and Standby VTCs VMs are paused and then resumed