---
# TimsProjectId=Tcbr2p TimsTestCaseId=Tcbr98c ShortDesription=In this test scenario we validate the impact of failing and recovering the standby VTC on the overall test environment.
- class: lab.monitors.vts_monitor.VtsMonitor
  duration: 200
  period: 2

- class: lab.scenarios.vts_scenario.VtsScenario
  delay: 20
  how-many-networks: 1
  how-many-servers: 2

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  delay: 20
  node-to-disrupt: passive-vtc
  how-many-times: 2
  downtime: 100
  uptime: 20

