---
- Folder: HIGH AVAILABILITY
- Description: test it statically - run VM create - ping - delete cycle parametrized number of steps, in paralell do the same with disruptor, then make sure from log timestemps that disrupting while VM was provisioning
              indeed happend at least once.

- class: lab.monitors.vts_monitor.VtsMonitor
  period: 2
  run_while:
    - vts-disruptor

- class: lab.scenarios.vts_delete_scenario.VtsDeleteScenario
  how-many-networks: 2
  how-many-servers: 10
  uptime: 120
  run_while:
    - vts-disruptor

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  delay: 20
  node-to-disrupt: master-dl
  method-to-disrupt: isolate-from-tenant
  n_repeats: 1
  downtime: 460
  uptime: 120
  set:
    - vts-disruptor

# Validate Standby XRNC becomes "Active' when Active XRNC¿s eth0 is shut while new tenant VMs are being deleted