---
# TimsProjectId=Tcbr2p TimsTestCaseId=Tcbr767c ShortDesription=Rebuild an instance and validate connectivity
- class: lab.scenarios.vts_scenario.VtsScenario
  delay: 10
  how-many-networks: 1
  how-many-servers: 1

- class: lab.monitors.vtf_monitor.VtfMonitor
  delay: 50
  how-many-times: 1

- class: lab.scenarios.server_rebuild.ServerRebuild
  delay: 60
  image: cirros-0.3.4-x86_64-disk.img

- class: lab.monitors.vtf_monitor.VtfMonitor
  delay: 100
  how-many-times: 1
