---
- Folder: HIGH AVAILABILITY
- Description: first create OS VM then start disruptor

- class: lab.monitors.vts_monitor.VtsMonitor
  run_while:
    - VtsDisruptor
  period: 2

- class: lab.scenarios.vts_scenario.VtsScenario
  how-many-networks: 1
  how-many-servers: 1
  what-to-run-inside: ping
  uptime: 20
  run_while:
    - VtsDisruptor

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  delay: 20
  node-to-disrupt: master-dl
  method-to-disrupt: ncs-stop
  n_repeats: 5
  downtime: 90
  uptime: 20
  set:
    - VtsDisruptor

# Possible nodes to disrupt: 'active-vtc', 'passive-vtc', 'active-dl', 'passive-dl'
# Possible methods:  'isolate-from-mx', 'isolate-from-api', 'vm-shutdown', 'vm-reboot', 'corosync-stop', 'ncs-stop'