---
# Project: Tcbr2p
# Id: Tcbr98c
# Title=Fail and Recover standby VTC
# Desription=In this test scenario we validate the impact of failing and recovering the standby VTC on the overall test environment.
- class: lab.monitors.vts_monitor.VtsMonitor
  duration: 200
  period: 2

- class: lab.scenarios.vts_scenario.VtsScenario
  delay: 20
  how-many-networks: 1
  how-many-servers: 2

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  delay: 20
  node-to-disrupt: passive-vtc
  method-to-disrupt: vm-shutdown
  how-many-times: 2
  downtime: 100
  uptime: 20

