---
- Folder: HIGH AVAILABILITY
- Description: first create OS VM then start disruptor

- class: lab.monitors.vts_monitor.VtsMonitor
  duration: 2000
  period: 2

- class: lab.scenarios.vts_scenario.VtsScenario
  how-many-networks: 1
  how-many-servers: 1
  n_repeats: 40

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  delay: 20
  node-to-disrupt: active-dl
  method-to-disrupt: ncs-stop
  n_repeats: 10
  downtime: 100
  uptime: 20

# Possible nodes to disrupt: 'active-vtc', 'passive-vtc', 'active-dl', 'passive-dl'
# Possible methods:  'isolate-from-mx', 'isolate-from-api', 'vm-shutdown', 'vm-reboot', 'corosync-stop', 'ncs-stop'