---
- Folder: HIGH AVAILABILITY
- Description: Validate Standby VTC is still running and in Standby mode when Standby VTC is rebooted while existing tenant VMs are also being deleted

- class: lab.monitors.vts_monitor.VtsMonitor
  name: VtsMonitor
  period: 2
  run_while:
    - VtsScenario
    - VtsDisruptor

- class: lab.scenarios.vts_scenario.VtsScenario
  name: VtsScenario
  how-many-networks: 2
  how-many-servers: 10
  what-to-run-inside: ping
  n_repeats: 10
  uptime: 30
  run_after:
    - VtsDisruptor

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: VtsDisruptor
  delay: 20
  node-to-disrupt: slave-vtc
  method-to-disrupt: vm-reboot
  n_repeats: 10
  downtime: 30
  uptime: 120
