---
# Project: Tcbr2p
# ID: Tcbr554c
# Title: Isolate the active VTC VM from the management network
# Description: In this test case active VTC VM will be isolated from the management network, but NOT from API network
- class: lab.monitors.vts_monitor.VtsMonitor
  duration: 200
  period: 2

- class: lab.scenarios.vts_scenario.VtsScenario
  delay: 20
  how-many-networks: 1
  how-many-servers: 3

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  delay: 20
  node-to-disrupt: master-vtc
  method-to-disrupt: isolate-from-mx
  how-many-times: 2
  downtime: 100
  uptime: 20

