---
- Folder: HIGH AVAILABILITY
- Description: tc_vts_passive_vtc_isolate_from_mx first create OS VM then set DOWN MX interface for a while
- class: lab.monitors.vts_monitor.VtsMonitor
  duration: 200
  period: 2

- class: lab.scenarios.vts_scenario.VtsScenario
  delay: 5
  how-many-networks: 1
  how-many-servers: 2
  n_repeats: 1

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  delay: 120
  node-to-disrupt: slave-vtc
  method-to-disrupt: isolate-from-mx
  n_repeats: 1
  downtime: 10
  uptime: 20

# Possible nodes to disrupt: 'active-vtc', 'passive-vtc', 'active-dl', 'passive-dl'
# Possible methods:  'isolate-from-mx', 'isolate-from-api', 'vm-shutdown', 'vm-reboot', 'corosync-stop', 'ncs-stop'