---
# TimsProjectId=Tcbr2p TimsTestCaseId=Tcbr102c ShortDesription=One of the two VTS control nodes are rebooted - repeat for other node
- class: lab.monitors.vts_monitor.VtsMonitor
  duration: 200
  period: 2

- class: lab.scenarios.vts_scenario.VtsScenario
  delay: 20
  how-many-networks: 1
  how-many-servers: 3

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  delay: 20
  node-to-disrupt: passive-xrvr
  how-many-times: 2
  downtime: 100
  uptime: 20

