
Folder: HIGH AVAILABILITY
Title: Active DL VTS libvirt VM shutdown
Description: first create OS VM then start disruptor
- class: lab.monitors.vts_monitor.VtsMonitor
  name: VtsMonitor
  delay: 0
  timeout: 1000
  pause: 2
  run:
    - VtsDisruptor

- class: lab.scenarios.vts_scenario.VtsScenario
  name: VtsScenario
  delay: 20
  run: [VtsDisruptor]
  pause: 0
  timeout: 1000
  n_networks: 1
  n_servers: 1
  run_inside: ping
  uptime: 20

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: VtsDisruptor
  delay: 200
  run: 1
  pause: 0
  timeout: 1000
  node_to_disrupt: master-dl
  method_to_disrupt: vm-shutdown
  disrupt_time: 20