---
- Folder: HIGH AVAILABILITY
- Description: first create OS VM then start disruptor

- class: lab.monitors.vts_monitor.VtsMonitor
  period: 2
  run_while:
    - vts-disruptor

- class: lab.scenarios.vts_scenario.VtsScenario
  delay: 100
  how-many-networks: 1
  how-many-servers: 3
  run_while:
    - vts-disruptor

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  delay: 3
  node-to-disrupt: master-vtc
  method-to-disrupt: vm-reboot
  n_repeats: 5
  downtime: 90
  uptime: 20
  set:
    - vts-disruptor

# Validate Standby VTC becomes "Active' when Active VTC is rebooted while Tenant VMs are also being created