---
# TimsProjectId=Tcbr2p TimsTestCaseId=Tcbr552c
# Title=Fail and recovery redudant DL VM Desription=Redundant DL VM is shut down or isolated from the network
- class: lab.monitors.vts_monitor.VtsMonitor
  duration: 200
  period: 2

- class: lab.scenarios.vts_scenario.VtsScenario
  delay: 20
  how-many-networks: 1
  how-many-servers: 3

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  delay: 20
  node-to-disrupt: passive-dl
  method-to-disrupt: vm-shutdown
  how-many-times: 2
  downtime: 100
  uptime: 20

