
Folder: HIGH AVAILABILITY
Title: Active DL ncs stop while adding OS servers
Description: test it statically - run VM create - ping - delete cycle parametrized number of steps, in paralell do the same with disruptor, then make sure from log timestemps that disrupting while VM was provisioning
              indeed happend at least once.

- class: lab.monitors.vts_monitor.VtsMonitor
  name: VtsMonitor
  delay: 0
  timeout: 1000
  pause: 2
  run:
    - VtsDisruptor

- class: lab.scenarios.vts_scenario.VtsScenario
  name: VtsScenario
  delay: 5
  timeout: 1000
  pause: 10
  n_networks: 1
  n_servers: 1
  run_inside: ping
  uptime: 20
  run:
    - VtsDisruptor

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: VtsDisruptor
  delay: 10
  timeout: 1000
  pause: 30
  node_to_disrupt: master-dl
  method_to_disrupt: ncs-stop
  run: 5
  disrupt_time: 20

# Possible nodes to disrupt: 'active-vtc', 'passive-vtc', 'active-dl', 'passive-dl'
# Possible methods:  'isolate-from-mx', 'isolate-from-api', 'vm-shutdown', 'vm-reboot', 'corosync-stop', 'ncs-stop'