---
- Folder: NEGATIVE
- Desription: In this test scenario we verify the behavior of the system when one of the OpenStack Controller fails and recovers.

- class: lab.monitors.vts_monitor.VtsMonitor
  run_while: [scenario-runnning, disruptor-running]
  period: 2

- class: lab.disruptors.cloud_disruptor.CloudDisruptor
  run_after: scenario-running
  disrupt: {controller-1: reboot}
  set: disruptor-running

- class: lab.scenarios.vts_scenario.VtsScenario
  delay: 20
  how-many-networks: 1
  how-many-servers: 3
  n_repeats: 1
  set: scenario-runnning


# Possible nodes to disrupt: 'active-vtc', 'passive-vtc', 'active-dl', 'passive-dl'
# Possible methods:  'isolate-from-mx', 'isolate-from-api', 'vm-shutdown', 'vm-reboot', 'corosync-stop', 'ncs-stop'