---
- Folder: HIGH AVAILABILITY
- Description: first create OS VM then start disruptor
  duration: 600
  period: 2

- class: lab.scenarios.vts_scenario.VtsScenario
  delay: 20
  how-many-networks: 1
  how-many-servers: 3
  n_repeats: 1

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  delay: 20
  node-to-disrupt: master-vtc
  method-to-disrupt: vm-shutdown
  n_repeats: 2
  downtime: 100
  uptime: 20

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  delay: 30
  node-to-disrupt: slave-dl
  method-to-disrupt: vm-shutdown
  n_repeats: 2
  downtime: 100
  uptime: 20

# Possible nodes to disrupt: 'active-vtc', 'passive-vtc', 'active-dl', 'passive-dl'
# Possible methods:  'isolate-from-mx', 'isolate-from-api', 'vm-shutdown', 'vm-reboot', 'corosync-stop', 'ncs-stop'