---
- Folder: HIGH AVAILABILITY
- Description: Validate Standby VTC becomes "Active' when Active VTC is rebooted while existing tenant VMs are also being deleted

- class: lab.monitors.vts_monitor.VtsMonitor
  period: 2
  run_while:
    - VtsDisruptor

- class: lab.scenarios.vts_delete_scenario.VtsDeleteScenario
  how-many-networks: 2
  how-many-servers: 10
  uptime: 120
  run_while:
    - VtsDisruptor

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  delay: 20
  node-to-disrupt: master-vtc
  method-to-disrupt: vm-reboot
  n_repeats: 1
  downtime: 460
  uptime: 120
  set:
    - VtsDisruptor

# Validate Standby VTC becomes "Active' when Active VTC is rebooted while existing tenant VMs are also being deleted