---
- Folder: PERFOMANCE AND SCALE
- Description: runs parametrised number of CSR images

- class: lab.scenarios.ntt_scenario.NttScenario
  how-many-networks: 3
  how-many-servers: 20
  n_repeats: 1
  delay: 10
