---
# Project: Tcbr2p
# Id: Tcbr102c
# Title: Fail and Recover OpenStack Controller Node
# Desription: In this test scenario we verify the behavior of the system when one of the OpenStack Controller fails and recovers.
- class: lab.monitors.vts_monitor.VtsMonitor
  duration: 200
  period: 2

- class: lab.scenarios.vts_scenario.VtsScenario
  delay: 20
  how-many-networks: 1
  how-many-servers: 3

- class: lab.disruptors.cloud_disruptor.VtsDisruptor
  delay: 20
  node-to-disrupt: passive-xrvr
  how-many-times: 2
  downtime: 100
  uptime: 20

