
Folder: HIGH AVAILABILITY
Title: Passive VTC reboot while adding OS servers
Description: Validate Standby VTC is still running and in Standby mode when Standby  VTC is rebooted while tenant VMs are also being created

- class: lab.monitors.vts_monitor.VtsMonitor
  name: VtsMonitor
  delay: 0
  timeout: 1000
  pause: 2
  run:
    - VtsDisruptor

- class: lab.scenarios.vts_scenario.VtsScenario
  name: VtsScenario
  delay: 0
  run: [VtsDisruptor]
  pause: 10
  timeout: 1000
  n_networks: 1
  n_servers: 3
  run_inside: ping
  uptime: 20

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: VtsDisruptor
  delay: 10
  run: 10
  pause: 30
  timeout: 1000
  node_to_disrupt: slave-vtc
  method_to_disrupt: vm-reboot
  disrupt_time: 20