
Folder: HIGH AVAILABILITY
Title: Passive VTC isolate from mx
Description: tc_vts_passive_vtc_isolate_from_mx first create OS VM then set DOWN MX interface for a while

- class: lab.monitors.vts_monitor.VtsMonitor
  name: VtsMonitor
  delay: 0
  run: [VtsScenario]
  pause: 2
  timeout: 1000

- class: lab.scenarios.vts_scenario.VtsScenario
  name: VtsScenario
  delay: 0
  run: 1
  pause: 0
  timeout: 1000
  n_networks: 1
  n_servers: 2
  run_inside: ping
  uptime: 400

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: VtsDisruptor
  delay: 200
  run: 1
  pause: 0
  timeout: 1000
  node_to_disrupt: slave-vtc
  method_to_disrupt: isolate-from-mx
  disrupt_time: 20