---
- Folder: HIGH AVAILABILITY
- Description: test it statically - run VM create - ping - delete cycle parametrized number of steps, in paralell do the same with disruptor, then make sure from log timestemps that disrupting while VM was provisioning
              indeed happend at least once.
- class: lab.monitors.vts_monitor.VtsMonitor
  duration: 200
  period: 2

- class: lab.scenarios.vts_scenario.VtsScenario
  delay: 20
  how-many-networks: 1
  how-many-servers: 3
  n_repeats: 1

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  delay: 20
  node-to-disrupt: master-dl
  method-to-disrupt: vm-shutdown
  n_repeats: 2
  downtime: 100
  uptime: 20

# Possible nodes to disrupt: 'active-vtc', 'passive-vtc', 'active-dl', 'passive-dl'
# Possible methods:  'isolate-from-mx', 'isolate-from-api', 'vm-shutdown', 'vm-reboot', 'corosync-stop', 'ncs-stop'