---
- Folder: HIGH AVAILABILITY
- Description: first create OS VM then start disruptor

- class: lab.monitors.vts_monitor.VtsMonitor
  period: 2
  run_while:
    - vts-disruptor-master-vtc
    - vts-disruptor-master-dl

- class: lab.scenarios.vts_scenario.VtsScenario
  delay: 110
  how-many-networks: 1
  how-many-servers: 3
  run_while:
    - vts-disruptor-master-vtc
    - vts-disruptor-master-dl

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  delay: 5
  node-to-disrupt: master-vtc
  method-to-disrupt: isolate-from-mx
  n_repeats: 1
  downtime: 90
  uptime: 20
  set:
    - vts-disruptor-master-vtc

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  delay: 5
  node-to-disrupt: master-dl
  method-to-disrupt: isolate-from-mx
  n_repeats: 1
  downtime: 90
  uptime: 20
  set:
    - vts-disruptor-master-dl

# Verify VM Creation during UNDERLAY Link failure on Active VTC/XRNC Controller