---
- Folder: HIGH AVAILABILITY
- Description: Validate Standby VTC becomes "Active' when Active VTC is rebooted while a compute node is added and deleted

- class: lab.monitors.vts_monitor.VtsMonitor
  name: VtsMonitor
  run_while:
    - VtsDisruptor

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: VtsDisruptor
  delay: 3
  downtime: 120
  uptime: 60
  node-to-disrupt: master-vtc
  method-to-disrupt: vm-reboot
  run_while:
    - VtsDeleteCompute
    - VtsAddCompute

- class: lab.scenarios.vts_delete_compute.VtsDeleteCompute
  name: VtsDeleteCompute
  n_repeats: 1

- class: lab.scenarios.vts_add_compute.VtsAddCompute
  name: VtsAddCompute
  run_after: VtsDeleteCompute
  n_repeats: 1
