---
- Folder: HIGH AVAILABILITY
- Description: first create OS VM then shutdown VTC master and DL slave

- class: lab.monitors.vts_monitor.VtsMonitor
  name: VtsMonitor
  period: 2
  run_while: [VtsScenario]

- class: lab.scenarios.vts_scenario.VtsScenario
  name: VtsScenario
  delay: 20
  how-many-networks: 1
  how-many-servers: 3
  what-to-run-inside: ping
  uptime: 20
  run_while: [VtsDisruptorVtcMaster, VtsDisruptorDlSlave]

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: VtsDisruptorVtcMaster
  delay: 5
  node-to-disrupt: master-vtc
  method-to-disrupt: vm-shutdown
  n_repeats: 2
  downtime: 100
  uptime: 20

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: VtsDisruptorDlSlave
  delay: 10
  node-to-disrupt: slave-dl
  method-to-disrupt: vm-shutdown
  n_repeats: 2
  downtime: 100
  uptime: 20

# Possible nodes to disrupt: 'active-vtc', 'passive-vtc', 'active-dl', 'passive-dl'
# Possible methods:  'isolate-from-mx', 'isolate-from-api', 'vm-shutdown', 'vm-reboot', 'corosync-stop', 'ncs-stop'