---
- Folder: HIGH AVAILABILITY
- Description: disrupt active vtc by downing mx iface while adding - deleting OS VM

- class: lab.monitors.vts_monitor.VtsMonitor
  name: VtsMonitor
  period: 2
  run_while:
    - VtsScenario

- class: lab.scenarios.vts_scenario.VtsScenario
  name: VtsScenario
  how-many-networks: 1
  how-many-servers: 3
  what-to-run-inside: ping
  uptime: 20
  run_while: VtsDisruptorVtcMaster

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: VtsDisruptorVtcMaster
  delay: 5
  node-to-disrupt: master-vtc
  method-to-disrupt: isolate-from-mx
  n_repeats: 10
  downtime: 90
  uptime: 20
