---
# Test Case TC806: Kill neutron-server on any controller node

- method: lab.monitors.ucsm_cluster_state
  duration: 800
  period: 1

- method: lab.monitors.ucsm_cluster_state
  name: UCSM_A
  duration: 800
  period: 1
  ip: 10.23.228.251

- method: lab.monitors.ucsm_cluster_state
  name: UCSM_B
  duration: 800
  period: 1
  ip: 10.23.228.252


- method: lab.monitors.service_endpoint
  service: neutron
  duration: 800
  period: 0.25

# Neutron-server on all control nodes
- method: lab.monitors.pgrep
  duration: 800
  period: 0.5
  node_name: control-0
  process: neutron-server
- method: lab.monitors.pgrep
  duration: 800
  period: 0.5
  node_name: control-1
  process: neutron-server
- method: lab.monitors.pgrep
  duration: 800
  period: 0.5
  node_name: control-2
  process: neutron-server
#
- method: lab.scenarios.tempest_test
  test: tempest.thirdparty.cisco.cvd.UCSMTest.test_create_delete_networks
  etime: 800
  git: https://github.com/cisco-openstack/tempest.git
  branch: proposed
  tempest_config_dir: /home/stack

- method: lab.scenarios.tempest_test
  test: tempest.thirdparty.cisco.cvd.UCSMTest.test_create_delete_networks
  etime: 800
  ramp_up_time: 6
  git: https://github.com/cisco-openstack/tempest.git
  branch: proposed
  tempest_config_dir: /home/stack

- method: lab.scenarios.tempest_test
  test: tempest.thirdparty.cisco.cvd.UCSMTest.test_create_delete_networks
  etime: 800
  ramp_up_time: 12
  git: https://github.com/cisco-openstack/tempest.git
  branch: proposed
  tempest_config_dir: /home/stack