# Test Case TC784: Power off undercloud node All OS services are operational while the node is offline
- method: lab.monitors.service_endpoint
  service: neutron
  duration: 100
  period: 1

- method: lab.monitors.service_endpoint
  service: nova
  duration: 100
  period: 1

- method: lab.monitors.ip_port
  name_or_ip: director
  duration: 100

- method: lab.monitors.ip_port
  name_or_ip: director
  duration: 100
