---
# Test Case TC786: Reboot compute node

- method: lab.scenarios.tempest_test
  test: test_connectivity_between_vms_on_different_networks
  etime: 700
  git: https://github.com/cisco-openstack/tempest.git
  branch: proposed

- method: lab.scenarios.tempest_test
  test: test_connectivity_between_vms_on_different_networks
  etime: 700
  ramp_up_time: 12
  git: https://github.com/cisco-openstack/tempest.git
  branch: proposed

- method: lab.scenarios.tempest_test
  test: test_connectivity_between_vms_on_different_networks
  etime: 700
  ramp_up_time: 24
  git: https://github.com/cisco-openstack/tempest.git
  branch: proposed

- method: lab.disruptors.reboot_node
  node_name: compute-0
  delay: 300

- method: lab.monitors.ip_port
  duration: 1000
  period: 2
  name_or_ip: compute-0
  port: 22
