---
# Test Case TC785: Reboot controller node

- method: lab.scenarios.tempest_test
  test: tempest.thirdparty.cisco.cvd.UCSMTest.test_create_delete_networks
  etime: 300
  git: https://github.com/cisco-openstack/tempest.git
  branch: proposed
  tempest_config_dir: /home/stack

- method: lab.scenarios.tempest_test
  test: tempest.thirdparty.cisco.cvd.UCSMTest.test_create_delete_networks
  etime: 294
  ramp_up_time: 6
  git: https://github.com/cisco-openstack/tempest.git
  branch: proposed
  tempest_config_dir: /home/stack

- method: lab.scenarios.tempest_test
  test: tempest.thirdparty.cisco.cvd.UCSMTest.test_create_delete_networks
  etime: 288
  ramp_up_time: 12
  git: https://github.com/cisco-openstack/tempest.git
  branch: proposed
  tempest_config_dir: /home/stack

- method: lab.disruptors.reboot_node
  node_name: controller-0
  delay: 100

- method: lab.monitors.ip_port
  duration: 500
  period: 2
  name_or_ip: controller-0
  port: 9696

- method: lab.monitors.service_endpoint
  service: neutron
  duration: 390
  period: 0.25