---
# Test Case TC806: Kill neutron-server on any controller node

- method: lab.monitors.service_endpoint
  type: network
  duration: 100
  period: 0.25

# Neutron-server on all control nodes
- method: lab.monitors.ip_port
  duration: 100
  period: 2
  ip: 10.11.12.107
  port: 9696
- method: lab.monitors.ip_port
  duration: 100
  period: 2
  ip: 10.11.12.109
  port: 9696
- method: lab.monitors.ip_port
  duration: 100
  period: 2
  ip: 10.11.12.104
  port: 9696

# Virtual IP.
- method: lab.monitors.ip_port
  duration: 100
  period: 2
  ip: 10.11.12.101
  port: 9696