---
# Test Case TC806: Kill neutron-server on any controller node

- method: lab.monitors.service_endpoint
  service: neutron
  duration: 390
  period: 0.25

# Neutron-server on all control nodes
- method: lab.monitors.pgrep
  duration: 390
  period: 0.5
  node_name: control-0
  process: neutron-server
- method: lab.monitors.pgrep
  duration: 390
  period: 0.5
  node_name: control-1
  process: neutron-server
- method: lab.monitors.pgrep
  duration: 390
  period: 0.5
  node_name: control-2
  process: neutron-server

- method: lab.scenarios.one_instance
  duration: 390

- method: lab.scenarios.one_instance
  duration: 390

- method: lab.scenarios.one_instance
  duration: 390

# Kill neutron-server on a controll
- method: lab.disruptors.pkill
  node_name: control-0
  process: neutron-server
  delay: 90
- method: lab.disruptors.pkill
  node_name: control-1
  process: neutron-server
  delay: 180
- method: lab.disruptors.pkill
  node_name: control-2
  process: neutron-server
  delay: 270