---
# Test Case TC812: Reboot N9k and FI Measure replay time

- method: lab.monitors.ip_port
  duration: 10
  period: 2
  name_or_ip: ucsm-0
- method: lab.monitors.ip_port
  duration: 10
  period: 2
  name_or_ip: n9k-1
- method: lab.monitors.ip_port
  duration: 10
  period: 2
  name_or_ip: n9k-2
- method: lab.monitors.ip_port
  duration: 10
  period: 2
  name_or_ip: control-0
  port: 9696
- method: lab.monitors.ip_port
  duration: 10
  period: 2
  name_or_ip: control-1
  port: 9696
- method: lab.monitors.ip_port
  duration: 10
  period: 2
  name_or_ip: control-2
  port: 9696
