# Test Case TC812: Reboot N9k and FI Measure replay time
- method: lab.monitors.ucsm
  duration: 6000
  period: 10
- method: lab.monitors.nexus
  duration: 6000
  period: 10
- method: lab.scenarios.net_subnet_port
  delay: 10
  how_many: 20
- method: lab.disruptors.n9k
  delay: 1000
  name_or_ip: from_lab
- method: lab.scenarios.delete
  delay: 2200
