---
# Test Case TC840: Evacuate primary fabric interconnect

- method: lab.disruptors.ucsm_evacuate
  fabric: a
  action: stop
  delay: 100

- method: lab.disruptors.ucsm_evacuate
  fabric: a
  action: start
  delay: 300


- method: lab.monitors.service_endpoint
  service: neutron
  duration: 800
  period: 0.25

# Neutron-server on all control nodes
- method: lab.monitors.pgrep
  duration: 800
  period: 0.5
  node_name: control-0
  process: neutron-server
- method: lab.monitors.pgrep
  duration: 800
  period: 0.5
  node_name: control-1
  process: neutron-server
- method: lab.monitors.pgrep
  duration: 800
  period: 0.5
  node_name: control-2
  process: neutron-server

- method: lab.scenarios.one_instance
  duration: 800

- method: lab.scenarios.one_instance
  duration: 800

- method: lab.scenarios.one_instance
  duration: 800