Folder: NEGATIVE
Title: Control node reboot
Description: Do OS instance create-ping once then in the middle do control reboot then delete OS instance
UniqueID: os-sqe-vts25
PossibleDrivers: [vts]
Workers:
- class: lab.monitors.vts_monitor.VtsMonitor
  name: VtsMonitor
  delay: 0
  run: [VtsScenario]
  pause: 2
  timeout: 1000

- class: lab.scenarios.vts_scenario.VtsScenario
  name: VtsScenario
  delay: 00
  run: 1
  pause: 0
  timeout: 1000
  n_networks: 1
  n_servers: 2
  run_inside: ping
  uptime: 400

- class: lab.disruptors.cloud_disruptor.CloudDisruptor
  name: CtlRebootDisruptor
  delay: 200
  run: 1
  pause: 0
  timeout: 1000
  node_to_disrupt: control
  method_to_disrupt: reboot
