Folder: HIGH AVAILABILITY
Title: Active DL reboot while adding compute node
Description: Do compute node delete-delete cycle, at the same time do active dl reboot in a cycle
UniqueID: os-sqe-vts26

Workers:
- class: lab.monitors.vts_monitor.VtsMonitor
  name: VtsMonitor
  delay: 0
  run: [VtsDisruptor]
  pause: 2
  timeout: 1000

- class: lab.disruptors.vts_disruptor.VtsDisruptor
  name: VtsDisruptor
  delay: 0
  run: [VtsDeleteCompute, VtsAddCompute]
  pause: 10
  timeout: 1000
  disrupt_time: 60
  node_to_disrupt: master-dl
  method_to_disrupt: vm-shutdown

- class: lab.scenarios.vts_delete_compute.VtsDeleteCompute
  name: VtsDeleteCompute
  delay: 0
  run: 1
  pause: 10
  timeout: 1000

- class: lab.scenarios.vts_add_compute.VtsAddCompute
  name: VtsAddCompute
  delay: [VtsDeleteCompute]
  run: 1
  pause: 10
  timeout: 1000
