---

- name: "Install openvswitch"
  yum:
    name: "{{ item }}"
  with_items:
    - openvswitch
- name: Enable openvswitch
  command: "systemctl enable openvswitch"
- name: Start openvswitch
  command: "systemctl start openvswitch"
