---

- name: "Install rpm packages"
  yum:
    name: "{{ item }}"
  with_items:
    - gcc
    - make
    - python-devel
    - python-twisted-core
    - python-zope-interface
    - PyQt4
    - groff
    - selinux-policy-devel
    - libcap-ng-devel
    - openssl-devel
    - kernel-devel
    - graphviz
    - kernel-debug-devel
    - autoconf
    - automake
    - rpm-build
    - redhat-rpm-config
    - libtool
    - libpcap-devel
- set_fact:
    ovs_version: 2.5.0
- name: "Delete rpmbuild folder"
  file:
    path: "{{ ansible_env.HOME }}/rpmbuild"
    state: absent
- name: "Create rpmbuild/SOURCES folder"
  file:
    path: "{{ ansible_env.HOME }}/rpmbuild/SOURCES"
    recurse: yes
    state: directory
- name: "Download openvswitch tarball {{ ovs_version }}"
  command: "curl -o {{ ansible_env.HOME }}/rpmbuild/SOURCES/openvswitch-{{ ovs_version }}.tar.gz http://openvswitch.org/releases/openvswitch-{{ ovs_version }}.tar.gz"
- name: "Extract openvswitch sources"
  unarchive:
    src: "{{ ansible_env.HOME }}/rpmbuild/SOURCES/openvswitch-{{ ovs_version }}.tar.gz"
    dest: "{{ ansible_env.HOME }}/rpmbuild/SOURCES"
    copy: no
- name: "Build openvswitch"
  command: "rpmbuild -bb --without check {{ ansible_env.HOME }}/rpmbuild/SOURCES/openvswitch-{{ ovs_version }}/rhel/openvswitch-fedora.spec"
- name: "Install"
  command: "rpm -Uvh {{ ansible_env.HOME }}/rpmbuild/RPMS/x86_64/openvswitch*"
- name: Enable openvswitch
  command: "systemctl enable openvswitch"
- name: Start openvswitch
  command: "systemctl start openvswitch"
