lab-id: 10 # integer in ranage (0,99). supposed to be unique in current L2 domain since used in MAC pools

# base creds will be used if not specified per node. service is a special creds to be used by OS neutron services
cred: {ssh_username: root, ssh_password: cisco123, ipmi_username: cobbler, ipmi_password: cobbler, neutron_username: neutron, neutron_password: cisco}

# describtion of lab's networks. name will be used to name vNIC which is wired to the network. mac-net-part is unique octet  which will be used in forming vNIC mac address
nets: {
  ipmi:     {                    vlan: [157],  cidr: 10.23.228.224/27}, # used for UCSM KVM IPMI
  user:     {mac-net-part: 'AA', vlan: [177],  cidr: 10.23.230.128/27}, # used for normal user traffic
  pxe-ext:  {mac-net-part: 'FF', vlan: [1],    cidr: 169.254.4.0/24,},  # used for external pxe bootstrapping of director
  pxe-int:  {mac-net-part: 'F0', vlan: [3333, 3000, 3001, 3002, 3003, 3004], cidr: 10.11.12.0/24},    # used for internal pxe bootstrapping of overcloud-node
  eth0:     {mac-net-part: 'E0', vlan: [3999] }, # used for eth0 network - current restriction of ucsm plugin will be renamed to api
  eth1:     {mac-net-part: 'E1', vlan: [3007, 177] }, # used for eth1 network - current restriction of ucsm plugin will be renamed to api
}

#names are supposed to be in form Role-XX where XX is some small integer
nodes: {
  nexus-1: {ip: 10.30.119.100, main_username: admin, main_password: CTO1234!, hostname: g10-N9K9372PX-2},
  nexus-2: {ip: 10.30.119.101, main_username: admin, main_password: CTO1234!, hostname: g10-N9K9372PX-3},

  fi-1: {ip: 10.23.228.251, vip: 10.23.228.253, main_username: admin, main_password: cisco, hostname: G10-UCS-6296UP-A},
  fi-2: {ip: 10.23.228.252, vip: 10.23.228.253, main_username: admin, main_password: cisco, hostname: G10-UCS-6296UP-B},

# ips are shifts for user and ipmi nets
  director-1:   {ip: -2, hostname: g10-director.ctocllab.cisco.com,                    nets: [user, eth1, pxe-ext, pxe-int]},
  control-1:    {ip: 4,                                               is-sriov: False, nets: [eth0, eth1, user, pxe-int]}, #  10.23.230.128
  control-2:    {ip: 5,                                               is-sriov: False, nets: [eth0, eth1, user, pxe-int]},
  control-3:    {ip: 6,                                               is-sriov: False, nets: [eth0, eth1, user, pxe-int]},
  compute-1:    {ip: 7,                                               is-sriov: False, nets: [eth0, eth1, user, pxe-int]},
  compute-2:    {ip: 8,                                               is-sriov: False, nets: [eth0, eth1, user, pxe-int]},
  compute-3:    {ip: 9,                                               is-sriov: False, nets: [eth0, eth1, user, pxe-int]},
  compute-4:    {ip: 10,                                               is-sriov: False, nets: [eth0, eth1, user, pxe-int]},

  cobbler-1:    {ip: 172.29.74.8, main_username: cobbler, main_password: cobbler}
}

# single wire is in the form pc_id: {South_Node_Name-port_id: North_Node_Name-port_id}.  Node name should match node from nodes section. IMPORTANT: should always be from south to north.
# if pc_id is integer, this pc_id will be created on corresponding devices.
# Port id for UCS is either server-id as discovered in UCSM
# If server controlled by CIMC then the format is node_name-id-pci_slot/uplink_port
wires: {
  101:   {nexus-1-1/16: nexus-2-1/16, nexus-1-1/17: nexus-2-1/17},
  81:    {fi-1-1/47: nexus-1-1/47, fi-1-1/48: nexus-2-1/47},
  82:    {fi-2-1/47: nexus-1-1/48, fi-2-1/48: nexus-2-1/48},
  fi3/1: {director-1-3/1:  fi-1-1/10, director-1-3/1: fi-2-1/10},
  fi1:   {control-1-1: fi-1-2/1/25, control-1-1: fi-2-2/1/25},
  fi2:   {control-2-2: fi-1-2/1/26, control-2-2: fi-2-2/1/26},
  fi3:   {control-3-3: fi-1-2/1/27, control-3-3: fi-2-2/1/27},
  fi4:   {compute-1-4: fi-1-2/1/28, compute-1-4: fi-2-2/1/28},
  fi5:   {compute-2-5: fi-1-2/1/29, compute-2-5: fi-2-2/1/29},
  fi6:   {compute-3-6: fi-1-2/1/30, compute-3-6: fi-2-2/1/30},
  fi7:   {compute-4-7: fi-1-2/1/31, compute-4-7: fi-2-2/1/31},
  cobbler: {cobbler-1-0/18: nexus-1-1/15, cobbler-1-0/17: nexus-2-1/15}
}

vlan_range: "1000:2999"
logstash: "172.29.173.236:5044"
rh-secret: http://172.29.173.233/redhat/osp7/redhat-developers-account.yaml  # login-password info for RH dev account used in director's registration
