lab-id: 8 # integer in ranage (0,99). supposed to be unique in current L2 domain since used in MAC pools

# base creds will be used if not specified per node. service is a special creds to be used by OS neutron services
cred: {ssh_username: root, ssh_password: cisco123, ipmi_username: cobbler, ipmi_password: cobbler, neutron_username: neutron, neutron_password: cisco}

use-sr-iov: False

# describtion of lab's networks. name will be used to name vNIC which is wired to the network. mac-net-part is unique octet  which will be used in forming vNIC mac address
nets: {
  ipmi:     {                    vlan: [8],                            cidr: 10.30.119.0/24},    # used for UCSM KVM IPMI
  user:     {mac-net-part: 'AA', vlan: [174],                          cidr: 10.23.230.64/27},   # used for normal ssh gw 10.23.230.65 (66,67) mask 255.255.255.224
  pxe-ext:  {mac-net-part: 'FF', vlan: [1],                            cidr: 169.254.4.0/24,},   # used for external pxe bootstrapping of director
  pxe-int:  {mac-net-part: 'F0', vlan: [3009, 3000, 3001, 3002, 3003], cidr: 10.11.12.0/24},     # used for internal pxe bootstrapping of overcloud-node
  eth0:     {mac-net-part: 'E0', vlan: [3899] },                                                 # used for eth0 network - tenant network
  eth1:     {mac-net-part: 'E1', vlan: [3007, 174] }                                             # used for eth1 network - external API network, fiP network
}

#names are supposed to be in form Role-XX where XX is some small integer
nodes: {
  tor-1:   {ip: None},

  nexus-1: {ip: 172.31.229.207, username: admin, password: CTO1234!, hostname: g08-N9K-9396PX-1},
  nexus-2: {ip: 172.31.230.234, username: admin, password: CTO1234!, hostname: g08-N9K-9396PX-2},

  asr-1:   {ip: 172.31.230.62,  username: admin, password:  CTO1234!, hostname: g08-ASR1001-X},

  fi-1:    {ip: 10.30.119.67, vip: 10.30.119.66, is-sriov: False, username: admin, password: cisco, hostname: g08-fi-A},
  fi-2:    {ip: 10.30.119.68, vip: 10.30.119.66, is-sriov: False, username: admin, password: cisco, hostname: g08-fi-B},

# ips are shifts for user and ipmi nets, id is server_id for UCS connected to fi, also used in generating mac address, so be sure it's in 1-99 and unique
  director-1: {ip: -2, hostname: g8-director.ctocllab.cisco.com,  nets: [user, eth1, pxe-ext, pxe-int]}, # ssh 10.23.230.94 ipmi 10.30.119.5
  control-1:  {ip: 4,                                             nets: [eth0, eth1, user, pxe-int]},    # ssh 10.23.230.69 ipmi 10.30.119.6
  control-2:  {ip: 5,                                             nets: [eth0, eth1, user, pxe-int]},    # ssh 10.23.230.70 ipmi 10.30.119.7
  control-3:  {ip: 6,                                             nets: [eth0, eth1, user, pxe-int]},    # ssh 10.23.230.71 ipmi 10.30.119.8

  compute-1:  {ip: 7, ipmi_ip: 10.30.119.93, ipmi_username: admin, ipmi_password: password, nets: [eth0, eth1, user, pxe-int]}, # 10.23.230.72
  compute-2:  {ip: 8, ipmi_ip: 10.30.119.94, ipmi_username: admin, ipmi_password: password, nets: [eth0, eth1, user, pxe-int]}, # 10.23.230.73

  cobbler-1: {ip: 172.29.74.8, username: cobbler, password: cobbler, nets: [pxe-ext]}
}

# single wire is in the form pc_id: {South_Node_Name-port_id: North_Node_Name-port_id}.  Node name should match node from nodes section. IMPORTANT: should always be from south to north.
# if pc_id starts with integer, this number will be used as (v)PC id on corresponding devices, if not this number will be assigned automatically
# UCS controlled by UCSM is e.g. control-1-5/a: fi-1-1/35  port_id=5/a means server_id=5 (C series) connected to FI-A,  port_id=3/1/b means server_id=3/1 connected to FI-B
# UCS controlled by CIMC is e.g. compute-1-3/0: nexus-1-1/3 port_id=3/0 means pci_slot=3 uplink_port=0
# all other port ids are usual ids as they used in NXOS
wires: {
  tor:  {nexus-1-1/1:  tor-1-1/1, nexus-2-1/1:  tor-1-1/4},
  peer: {nexus-1-1/31:  nexus-2-1/31, nexus-1-1/33: nexus-2-1/33, nexus-1-1/35: nexus-2-1/35},

  fi1-n9:  {fi-1-1/9: nexus-1-1/9, fi-1-1/10: nexus-2-1/9},
  fi2-n9:  {fi-2-1/9: nexus-1-1/10, fi-2-1/10: nexus-2-1/10},

  ucs-1:   {director-1-1/a: fi-1-1/3, director-1-1/b: fi-2-1/3},
  ucs-2:   {control-1-2/a: fi-1-1/4,  control-1-2/b: fi-2-1/4},
  ucs-3:   {control-2-3/a: fi-1-1/5,  control-2-3/b: fi-2-1/4},
  ucs-4:   {control-3-4/a: fi-1-1/6,  control-3-4/b: fi-2-1/4},

  cimc-1: {compute-1-3/0: nexus-1-1/3},
  cimc-2: {compute-2-3/0: nexus-2-1/4},
  cobbler: {cobbler-1-0/18: nexus-1-1/15, cobbler-1-0/17: nexus-2-1/15},

  n9-asr: {nexus-1-1/48: asr-1-0/0, nexus-2-1/48: asr-1-0/1}
}

vlan_range: "1000:2000"
rh-secret: http://172.29.173.233/redhat/osp7/redhat-developers-account.yaml  # login-password info for RH dev account used in director's registration
connection_type: vlan
logstash: "172.29.173.236:9999"