lab-id: 13 # integer in ranage (0,99). supposed to be unique in current L2 domain since used in MAC pools

# base creds will be used if not specified per node. service is a special creds to be used by OS neutron services
cred: {ssh_username: root, ssh_password: cisco123, ipmi_username: admin, ipmi_password: cisco123, neutron_username: neutron, neutron_password: cisco}

use-sr-iov: False

# describtion of lab's networks. name will be used to name vNIC which is wired to the network. mac-net-part is unique octet  which will be used in forming vNIC mac address
nets: {
  ipmi:     {                    vlan: [],                             cidr: 172.31.230},                  # used for UCSM KVM IPMI
  user:     {mac-net-part: 'AA', vlan: [112],                          cidr: 10.30.117.0/28},    # used for normal ssh gw 10.30.117.1 (2,3) mask 255.255.255.224
  pxe-ext:  {mac-net-part: 'FF', vlan: [1],                            cidr: 169.254.4.0/24,},   # used for external pxe bootstrapping of director
  eth0:     {mac-net-part: 'E0', vlan: [3899] },                                                 # used for eth0 network - tenant network
}

#names are supposed to be in form Role-XX where XX is some small integer
nodes: {
  tor-1:   {ip: None},

  nexus-1: {ip: 172.31.230.92, username: admin, password: CTO1234!, hostname: i13-N9372PX-3},

#  control-1:  {ip: 4, ipmi_ip: 172.21.230.105, nets: [eth0, eth1, user, pxe-int]},  #  currently experience connectivity issue!
  control-1:  {ip: 5, ipmi_ip: 172.21.230.106, nets: [eth0, user]},
  control-2:  {ip: 6, ipmi_ip: 172.21.230.107, nets: [eth0, user]},
  control-3:  {ip: 7, ipmi_ip: 172.21.230.108, nets: [eth0, user]},
  compute-1:  {ip: 8, ipmi_ip: 172.21.230.109, nets: [eth0, user]},
  build-1:    {ip: 9, ipmi_ip: 172.21.230.110, nets: [eth0, user]},

  cobbler-1: {ip: 172.29.74.8, username: cobbler, password: cobbler, nets: [pxe-ext]}
}

# single wire is in the form pc_id: {South_Node_Name-port_id: North_Node_Name-port_id}.  Node name should match node from nodes section. IMPORTANT: should always be from south to north.
# if pc_id starts with integer, this number will be used as (v)PC id on corresponding devices, if not this number will be assigned automatically
# UCS controlled by UCSM is e.g. control-1-5/a: fi-1-1/35  port_id=5/a means server_id=5 (C series) connected to FI-A,  port_id=3/1/b means server_id=3/1 connected to FI-B
# UCS controlled by CIMC is e.g. compute-1-3/0: nexus-1-1/3 port_id=3/0 means pci_slot=3 uplink_port=0
# all other port ids are usual ids as they used in NXOS
wires: {
  tor:  {nexus-1-1/48:  tor-1-1/45},


#  cimc-1: {compute-1-3/0: nexus-1-1/6, compute-1-3/1: nexus-1-1/11}, # ipmi .105
  cimc-2: {control-1-3/0: nexus-1-1/5, control-1-3/1: nexus-1-1/12},  # ipmi .106
  cimc-3: {control-2-3/0: nexus-1-1/4, control-2-3/1: nexus-1-1/13},  # ipmi .107
  cimc-4: {control-3-3/0: nexus-1-1/3, control-3-3/1: nexus-1-1/14},  # ipmi .108
  cimc-5: {compute-1-3/0: nexus-1-1/2, compute-1-3/1: nexus-1-1/15},  # ipmi .109
  cimc-6: {build-1-3/0:   nexus-1-1/1, build-1-3/1:   nexus-1-1/16},  # ipmi .110

  cobbler: {cobbler-1-0/18: nexus-1-1/15, cobbler-1-0/17: nexus-2-1/15},
}

vlan_range: "1000:2000"
rh-secret: http://172.29.173.233/redhat/osp7/redhat-developers-account.yaml  # login-password info for RH dev account used in director's registration
connection_type: vlan
logstash: "172.29.173.236:9999"