---
  NovaServers.boot_multiple_servers_with_nic:
    -
      args:
        image:
          name: "cirros 0.3.4"
        flavor:
          name: "m1.tiny"
        count: 2
        network_create_args: {}
        subnet_create_args: {}
        subnet_cidr_start: "1.2.0.0/24"
        subnets_per_network: 1
      runner:
        type: "constant"
        times: {n_times}
        concurrency: {concurrency}
      context:
        network: {}
        users:
          tenants: {n_tenants}
          users_per_tenant: 1
        quotas:
          neutron:
            network: -1
            subnet: -1
