---

- name: G10 playbook
  hosts: g10
  gather_facts: no

  tasks:

    - name: delete vlans all if state "absent"
      nxos_vlan:
        vlan_id: "2-3967"
        host: "{{ inventory_hostname }}"
        state: "absent"
      when: state == "absent"
    - name: Reset all allowed vlans to 1
      nxos_switchport:
        interface: "Po{{ item }}"
        mode: trunk
        trunk_vlans: "1"
        host: "{{ inventory_hostname }}"
        state: "present"
      when: state == "absent"
      with_items:
        - "{{ uplink_port_channel }}"
        - "{{ peer_link_channel }}"
        - "{{ fabric_a_port_channel }}"
        - "{{ fabric_b_port_channel }}"

    - name: create vlans
      nxos_vlan:
        vlan_id: "{{ uplink_vlans }}, {{ server_vlans }}"
        host: "{{ inventory_hostname }}"
        state: "{{ state }}"
    - name: create port-channels
      nxos_portchannel:
        group: "{{ item.channel }}"
        members: "{{ item.ports }}"
        mode: active
        host: "{{ inventory_hostname }}"
        state: "{{ state }}"
      with_items:
        - channel: "{{ uplink_port_channel }}"
          ports: "{{ uplink_ports }}"
        - channel: "{{ peer_link_channel }}"
          ports: "{{ peer_link_ports }}"
        - channel: "{{ fabric_a_port_channel }}"
          ports: "{{ fabric_a_ports }}"
        - channel: "{{ fabric_b_port_channel }}"
          ports: "{{ fabric_b_ports }}"
    - name: config port-channels
      nxos_interface: interface=Po{{ item.channel }} mode=layer2 host={{ inventory_hostname }} state={{ state }}
      with_items:
        - channel: "{{ uplink_port_channel }}"
        - channel: "{{ peer_link_channel }}"
        - channel: "{{ fabric_a_port_channel }}"
        - channel: "{{ fabric_b_port_channel }}"
    - name: add vlans to port-channels
      nxos_switchport:
        interface: "Po{{ item.channel }}"
        mode: trunk
        trunk_vlans: "{{ item.vlans }}"
        host: "{{ inventory_hostname }}"
        state: "{{ state }}"
      when: state == "present"
      with_items:
        - channel: "{{ uplink_port_channel }}"
          vlans: "{{ uplink_vlans }}"
        - channel: "{{ peer_link_channel }}"
          vlans: "{{ server_vlans }}"
        - channel: "{{ fabric_a_port_channel }}"
          vlans: "{{ server_vlans }}"
        - channel: "{{ fabric_b_port_channel }}"
          vlans: "{{ server_vlans }}"
    - name: create VPCs
      nxos_vpc_interface:
        portchannel: "{{ item.channel  }}"
        vpc: "{{ item.channel  }}"
        host: "{{ inventory_hostname }}"
        state: "{{ state }}"
      with_items:
        - channel: "{{ uplink_port_channel }}"
        - channel: "{{ fabric_a_port_channel }}"
        - channel: "{{ fabric_b_port_channel }}"
    - name: create peer-link VPC
      nxos_vpc_interface:
        portchannel: "{{ peer_link_channel  }}"
        peer_link: true
        host: "{{ inventory_hostname }}"
        state: "{{ state }}"
