---

- name: G8 playbook
  hosts: g8
  gather_facts: no

  tasks:

    - name: config server ports
      nxos_interface:
        interface: "{{ item }}"
        mode: layer2
        host: "{{ inventory_hostname }}"
        state: "{{ state }}"
      with_items:
        "{{ server_ports }}"
    - name: add vlans to server ports
      nxos_switchport:
        interface: "{{ item }}"
        mode: trunk
        trunk_vlans: none
        host: "{{ inventory_hostname }}"
        state: "{{ state }}"
      when: state == "present"
      with_items:
        "{{ server_ports }}"

    - name: config server ports
      nxos_interface:
        interface:  "Po{{ peer_link_channel }}"
        host: "{{ inventory_hostname }}"
        admin_state: down
        state: present