---

- name: G8 UCSM playbook
  hosts: ucsm
  gather_facts: no
  tasks:
    - shell: pwd
    - name: Clear UCSM
      shell: "fab ucsm.cleanup:{{ ucsm_vip }},{{ ucsm_user }},{{ ucsm_password }}"
    - name: Configure UCSM
      shell: "fab ucsm.configure_for_osp7:../lab/configs/labs/g8.yaml"
