---

- name: G8 vxlan playbook
  hosts: g8
  gather_facts: no

  tasks:

    - nxos_feature:
        feature: ospf
        state: enabled
        host: "{{ inventory_hostname }}"

    - nxos_feature:
        feature: pim
        state: enabled
        host: "{{ inventory_hostname }}"

    - name: Create loopback interfaces
      nxos_interface:
        interface: "{{ item }}"
        host: "{{ inventory_hostname }}"
        state: "{{ state }}"
      with_items:
        - loopback1
        - loopback2

    - name: Set IP address of a loopback1
      nxos_ipv4_interface:
        interface: loopback1
        ip_addr: "{{ lo1_ip }}"
        ip_router_ospf: "{{ router_ospf }}"
        ip_router_area: "{{ router_area }}"
        ip_pim_sparse_mode: True
        mask: 32
        host: "{{ inventory_hostname }}"
        state: "{{ state }}"
      when: state == "present"

    - name: Set IP address of a loopback2
      nxos_ipv4_interface:
        interface: loopback2
        ip_addr: "{{ lo2_ip }}"
        ip_router_ospf: "{{ router_ospf }}"
        ip_router_area: "{{ router_area }}"
        ip_pim_sparse_mode: True
        mask: 32
        host: "{{ inventory_hostname }}"
        state: "{{ state }}"
      when: state == "present"

    - name: Set mode of eth1/48 to layer3
      nxos_interface:
        interface: Eth1/48
        mode: layer3
        host: "{{ inventory_hostname }}"
        state: "{{ state }}"

    - name: Set IP address of eth1/48
      nxos_ipv4_interface:
        interface: Eth1/48
        ip_addr: "{{ eth48_ip }}"
        ip_router_ospf: "{{ router_ospf }}"
        ip_router_area: "{{ router_area }}"
        ip_pim_sparse_mode: True
        mask: 30
        host: "{{ inventory_hostname }}"
        state: "{{ state }}"
      when: state == "present"