---

- name: G8 playbook
  hosts: g8
  gather_facts: no

  tasks:

    - name: create vlans
      nxos_vlan:
        vlan_id: "{{ uplink_vlans }}, {{ server_vlans }}"
        host: "{{ inventory_hostname }}"
        state: "{{ state }}"
    - name: create port-channels
      nxos_portchannel:
        group: "{{ item.channel }}"
        members: "{{ item.ports }}"
        mode: active
        host: "{{ inventory_hostname }}"
        state: "{{ state }}"
      with_items:
        - channel: "{{ uplink_port_channel }}"
          ports: "{{ uplink_ports }}"
        - channel: "{{ peer_link_channel }}"
          ports: "{{ peer_link_ports }}"
        - channel: "{{ fabric_a_port_channel }}"
          ports: "{{ fabric_a_ports }}"
        - channel: "{{ fabric_b_port_channel }}"
          ports: "{{ fabric_b_ports }}"
    - name: config port-channels
      nxos_interface: interface=Po{{ item.channel }} mode=layer2 host={{ inventory_hostname }} state={{ state }}
      with_items:
        - channel: "{{ uplink_port_channel }}"
        - channel: "{{ peer_link_channel }}"
        - channel: "{{ fabric_a_port_channel }}"
        - channel: "{{ fabric_b_port_channel }}"
    - name: add vlans to port-channels
      nxos_switchport:
        interface: "Po{{ item.channel }}"
        mode: trunk
        trunk_vlans: "{{ item.vlans }}"
        host: "{{ inventory_hostname }}"
        state: "{{ state }}"
      when: state == "present"
      with_items:
        - channel: "{{ uplink_port_channel }}"
          vlans: "{{ uplink_vlans }}"
        - channel: "{{ peer_link_channel }}"
          vlans: "{{ server_vlans }}"
        - channel: "{{ fabric_a_port_channel }}"
          vlans: "{{ server_vlans }}"
        - channel: "{{ fabric_b_port_channel }}"
          vlans: "{{ server_vlans }}"
    - name: create vpc domain
      nxos_vpc:
        domain: 1
        pkl_src: "{{ source }}"
        pkl_dest: "{{ peer_keapalive }}"
        host: "{{ inventory_hostname }}"
    - name: create VPCs
      nxos_vpc_interface:
        portchannel: "{{ item.channel  }}"
        vpc: "{{ item.channel  }}"
        host: "{{ inventory_hostname }}"
        state: "{{ state }}"
      with_items:
        - channel: "{{ uplink_port_channel }}"
        - channel: "{{ fabric_a_port_channel }}"
        - channel: "{{ fabric_b_port_channel }}"
    - name: create peer-link VPC
      nxos_vpc_interface:
        portchannel: "{{ peer_link_channel  }}"
        peer_link: true
        host: "{{ inventory_hostname }}"
        state: "{{ state }}"
